///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace NG_Demo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the NG_DemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("a62bc3c8-5e8d-4914-8fab-2636add9488c")]
    public partial class NG_DemoRepository : RepoGenBaseFolder
    {
        static NG_DemoRepository instance = new NG_DemoRepository();
        NG_DemoRepositoryFolders.FormVipApplicationAppFolder _formvipapplication;
        NG_DemoRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder _ranorexvipdatabasetestwebapplicatio;

        /// <summary>
        /// Gets the singleton class instance representing the NG_DemoRepository element repository.
        /// </summary>
        [RepositoryFolder("a62bc3c8-5e8d-4914-8fab-2636add9488c")]
        public static NG_DemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public NG_DemoRepository() 
            : base("NG_DemoRepository", "/", null, 0, false, "a62bc3c8-5e8d-4914-8fab-2636add9488c", ".\\RepositoryImages\\NG_DemoRepositorya62bc3c8.rximgres")
        {
            _formvipapplication = new NG_DemoRepositoryFolders.FormVipApplicationAppFolder(this);
            _ranorexvipdatabasetestwebapplicatio = new NG_DemoRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a62bc3c8-5e8d-4914-8fab-2636add9488c")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormVipApplication folder.
        /// </summary>
        [RepositoryFolder("32ff32bd-1f2f-4b96-b134-8fc754fc0880")]
        public virtual NG_DemoRepositoryFolders.FormVipApplicationAppFolder FormVipApplication
        {
            get { return _formvipapplication; }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatio folder.
        /// </summary>
        [RepositoryFolder("33c0e106-5622-491d-b674-7a0b195c47f7")]
        public virtual NG_DemoRepositoryFolders.RanorexVIPDatabaseTestWebApplicatioAppFolder RanorexVIPDatabaseTestWebApplicatio
        {
            get { return _ranorexvipdatabasetestwebapplicatio; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class NG_DemoRepositoryFolders
    {
        /// <summary>
        /// The FormVipApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("32ff32bd-1f2f-4b96-b134-8fc754fc0880")]
        public partial class FormVipApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _rbmaleInfo;
            RepoItemInfo _btaddInfo;
            RepoItemInfo _vipcount1Info;
            RepoItemInfo _btclearInfo;
            RepoItemInfo _vipcount0Info;

            /// <summary>
            /// Creates a new FormVipApplication  folder.
            /// </summary>
            public FormVipApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormVipApplication", "/form[@controlname='formVipApplication']", parentFolder, 30000, null, true, "32ff32bd-1f2f-4b96-b134-8fc754fc0880", "")
            {
                _fnameInfo = new RepoItemInfo(this, "FName", "?/?/text[@accessiblename='First Name:']", 60000, null, "cb1b23c1-b5c6-4eac-8b73-ce1743dbce24");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:']", 60000, null, "38be0a25-39d3-46ac-bae6-5494437d7b6f");
                _musicInfo = new RepoItemInfo(this, "Music", ".//listitem[@accessiblename='Music']", 60000, null, "a306aca4-2132-4349-8711-5a48c312e4c6");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//listitem[@accessiblename='Movie']", 60000, null, "efa97b0b-ca2c-4849-8df7-62e6c672af5d");
                _rbmaleInfo = new RepoItemInfo(this, "RbMale", "?/?/radiobutton[@controlname='rbMale']", 60000, null, "8cc0e916-9ece-4c3b-ac93-89625e0995be");
                _btaddInfo = new RepoItemInfo(this, "BtAdd", "button[@controlname='btAdd']", 60000, null, "648f0c6a-8165-4a40-b12f-bc8723f14c4e");
                _vipcount1Info = new RepoItemInfo(this, "VIPCount1", "?/?/text[@accessiblename='VIP count: 1']", 60000, null, "bb907601-c8d9-4dcc-9d7e-f53a932856b0");
                _btclearInfo = new RepoItemInfo(this, "BtClear", "button[@controlname='btClear']", 60000, null, "d835f7c3-129a-4ef9-b6f7-cf1a4784182a");
                _vipcount0Info = new RepoItemInfo(this, "VIPCount0", "?/?/text[@accessiblename='VIP count: 0']", 60000, null, "a4a0884b-1176-472d-9aaf-9af8a69c3e85");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32ff32bd-1f2f-4b96-b134-8fc754fc0880")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32ff32bd-1f2f-4b96-b134-8fc754fc0880")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FName item.
            /// </summary>
            [RepositoryItem("cb1b23c1-b5c6-4eac-8b73-ce1743dbce24")]
            public virtual Ranorex.Text FName
            {
                get
                {
                    return _fnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FName item info.
            /// </summary>
            [RepositoryItemInfo("cb1b23c1-b5c6-4eac-8b73-ce1743dbce24")]
            public virtual RepoItemInfo FNameInfo
            {
                get
                {
                    return _fnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("38be0a25-39d3-46ac-bae6-5494437d7b6f")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("38be0a25-39d3-46ac-bae6-5494437d7b6f")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("a306aca4-2132-4349-8711-5a48c312e4c6")]
            public virtual Ranorex.ListItem Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("a306aca4-2132-4349-8711-5a48c312e4c6")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("efa97b0b-ca2c-4849-8df7-62e6c672af5d")]
            public virtual Ranorex.ListItem Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("efa97b0b-ca2c-4849-8df7-62e6c672af5d")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The RbMale item.
            /// </summary>
            [RepositoryItem("8cc0e916-9ece-4c3b-ac93-89625e0995be")]
            public virtual Ranorex.RadioButton RbMale
            {
                get
                {
                    return _rbmaleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The RbMale item info.
            /// </summary>
            [RepositoryItemInfo("8cc0e916-9ece-4c3b-ac93-89625e0995be")]
            public virtual RepoItemInfo RbMaleInfo
            {
                get
                {
                    return _rbmaleInfo;
                }
            }

            /// <summary>
            /// The BtAdd item.
            /// </summary>
            [RepositoryItem("648f0c6a-8165-4a40-b12f-bc8723f14c4e")]
            public virtual Ranorex.Button BtAdd
            {
                get
                {
                    return _btaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtAdd item info.
            /// </summary>
            [RepositoryItemInfo("648f0c6a-8165-4a40-b12f-bc8723f14c4e")]
            public virtual RepoItemInfo BtAddInfo
            {
                get
                {
                    return _btaddInfo;
                }
            }

            /// <summary>
            /// The VIPCount1 item.
            /// </summary>
            [RepositoryItem("bb907601-c8d9-4dcc-9d7e-f53a932856b0")]
            public virtual Ranorex.Text VIPCount1
            {
                get
                {
                    return _vipcount1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount1 item info.
            /// </summary>
            [RepositoryItemInfo("bb907601-c8d9-4dcc-9d7e-f53a932856b0")]
            public virtual RepoItemInfo VIPCount1Info
            {
                get
                {
                    return _vipcount1Info;
                }
            }

            /// <summary>
            /// The BtClear item.
            /// </summary>
            [RepositoryItem("d835f7c3-129a-4ef9-b6f7-cf1a4784182a")]
            public virtual Ranorex.Button BtClear
            {
                get
                {
                    return _btclearInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The BtClear item info.
            /// </summary>
            [RepositoryItemInfo("d835f7c3-129a-4ef9-b6f7-cf1a4784182a")]
            public virtual RepoItemInfo BtClearInfo
            {
                get
                {
                    return _btclearInfo;
                }
            }

            /// <summary>
            /// The VIPCount0 item.
            /// </summary>
            [RepositoryItem("a4a0884b-1176-472d-9aaf-9af8a69c3e85")]
            public virtual Ranorex.Text VIPCount0
            {
                get
                {
                    return _vipcount0Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The VIPCount0 item info.
            /// </summary>
            [RepositoryItemInfo("a4a0884b-1176-472d-9aaf-9af8a69c3e85")]
            public virtual RepoItemInfo VIPCount0Info
            {
                get
                {
                    return _vipcount0Info;
                }
            }
        }

        /// <summary>
        /// The RanorexVIPDatabaseTestWebApplicatioAppFolder folder.
        /// </summary>
        [RepositoryFolder("33c0e106-5622-491d-b674-7a0b195c47f7")]
        public partial class RanorexVIPDatabaseTestWebApplicatioAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _movieInfo;
            RepoItemInfo _genderInfo;
            RepoItemInfo _inputtagaddInfo;
            RepoItemInfo _countInfo;

            /// <summary>
            /// Creates a new RanorexVIPDatabaseTestWebApplicatio  folder.
            /// </summary>
            public RanorexVIPDatabaseTestWebApplicatioAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RanorexVIPDatabaseTestWebApplicatio", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "33c0e106-5622-491d-b674-7a0b195c47f7", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'FirstName']", 60000, null, "3e316916-9446-4669-a536-3c7078b18a4c");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'LastName']", 60000, null, "23dd47e1-b734-42bb-8c54-f862310ece7a");
                _movieInfo = new RepoItemInfo(this, "Movie", ".//select[#'Category']/option[@value='Movie']", 60000, null, "50a12c8e-d4e1-4bbc-81df-a9e4cffdca30");
                _genderInfo = new RepoItemInfo(this, "Gender", ".//td[#'gender']//input[@name='Gender' and @type='radio' and @value='male']", 60000, null, "0e9c9752-067e-4958-b83d-7fbc37971bf5");
                _inputtagaddInfo = new RepoItemInfo(this, "InputTagAdd", ".//input[#'Add']", 60000, null, "433934f1-b81e-4e02-a2a6-fd400a588de3");
                _countInfo = new RepoItemInfo(this, "Count", ".//td[#'count']", 60000, null, "ba337c2c-928a-43b4-9cb5-f8cc56fe1cd8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("33c0e106-5622-491d-b674-7a0b195c47f7")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("33c0e106-5622-491d-b674-7a0b195c47f7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("3e316916-9446-4669-a536-3c7078b18a4c")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("3e316916-9446-4669-a536-3c7078b18a4c")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("23dd47e1-b734-42bb-8c54-f862310ece7a")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("23dd47e1-b734-42bb-8c54-f862310ece7a")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Movie item.
            /// </summary>
            [RepositoryItem("50a12c8e-d4e1-4bbc-81df-a9e4cffdca30")]
            public virtual Ranorex.OptionTag Movie
            {
                get
                {
                    return _movieInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The Movie item info.
            /// </summary>
            [RepositoryItemInfo("50a12c8e-d4e1-4bbc-81df-a9e4cffdca30")]
            public virtual RepoItemInfo MovieInfo
            {
                get
                {
                    return _movieInfo;
                }
            }

            /// <summary>
            /// The Gender item.
            /// </summary>
            [RepositoryItem("0e9c9752-067e-4958-b83d-7fbc37971bf5")]
            public virtual Ranorex.InputTag Gender
            {
                get
                {
                    return _genderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Gender item info.
            /// </summary>
            [RepositoryItemInfo("0e9c9752-067e-4958-b83d-7fbc37971bf5")]
            public virtual RepoItemInfo GenderInfo
            {
                get
                {
                    return _genderInfo;
                }
            }

            /// <summary>
            /// The InputTagAdd item.
            /// </summary>
            [RepositoryItem("433934f1-b81e-4e02-a2a6-fd400a588de3")]
            public virtual Ranorex.InputTag InputTagAdd
            {
                get
                {
                    return _inputtagaddInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAdd item info.
            /// </summary>
            [RepositoryItemInfo("433934f1-b81e-4e02-a2a6-fd400a588de3")]
            public virtual RepoItemInfo InputTagAddInfo
            {
                get
                {
                    return _inputtagaddInfo;
                }
            }

            /// <summary>
            /// The Count item.
            /// </summary>
            [RepositoryItem("ba337c2c-928a-43b4-9cb5-f8cc56fe1cd8")]
            public virtual Ranorex.TdTag Count
            {
                get
                {
                    return _countInfo.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The Count item info.
            /// </summary>
            [RepositoryItemInfo("ba337c2c-928a-43b4-9cb5-f8cc56fe1cd8")]
            public virtual RepoItemInfo CountInfo
            {
                get
                {
                    return _countInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
